name: Automation Trigger

# 1. Trigger: Eppudu run avvali?
on:
  push:
    branches:
      - main  # Meeru code push chesinappudalla script run avthundi

jobs:
  build:
    runs-on: ubuntu-latest # GitHub manaki oka Linux server isthundi

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2 # Mana code ni server loki teesukosthundhi
            # trigger test
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install requests

    - name: Run Python Script
      env:
        # Ikkada magic! GitHub Secrets nundi token teesukuntundi
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: python test.py
